# Generated by Django 5.2 on 2025-07-25 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=200)),
                ('confidence', models.FloatField(default=0.0)),
                ('image_path', models.CharField(max_length=500)),
                ('is_healthy', models.BooleanField(default=True)),
                ('class_name', models.CharField(default='', max_length=100)),
                ('matched_plant_id', models.IntegerField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plant Analysis',
                'verbose_name_plural': 'Plant Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
