# Generated by Django 5.2.3 on 2025-06-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/plant/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/soil/')),
                ('description', models.TextField()),
                ('plants', models.ManyToManyField(blank=True, related_name='soils', to='soil.plant')),
            ],
        ),
    ]
